#!/usr/bin/env bash

# This script permission have to 755.
# It is used in /etc/update-motd.d.
# Follow this:
#   cd /etc/update-motd.d/; ln -s <SCRIPT_PATH> ./

echo -e ""
echo -e " * `uptime -p`"

MIN_VER="3.3.10"
FREE_VER="`free -V | awk '{print $4}'`"
if [ "`printf "%s\n" "$MIN_VER" "$FREE_VER" | sort -V | head -n1`" == "$MIN_VER" ]; then
	TOTAL_MEM=`free | grep -v total | grep -v Swap | grep -v buff | awk '{print $2}'`
	AVAILABLE_MEM=`free | grep -v total | grep -v Swap | grep -v buff | awk '{print $7}'`
	USED_MEM_PER=`expr 100 '-' '(' ${AVAILABLE_MEM} '*' 100 '/' ${TOTAL_MEM} ')'`

	TOTAL_MEM=`free -h | grep -v total | grep -v Swap | grep -v buff | awk '{print $2}'`
	AVAILABLE_MEM=`free -h | grep -v total | grep -v Swap | grep -v buff | awk '{print $7}'`

	echo -e " * Memory usage    \t${USED_MEM_PER}%"
	echo -e " * Available memory\t${AVAILABLE_MEM} of ${TOTAL_MEM}"
fi
